model:
  name: deeplabv3_resnet101
  cls: torch.hub.load
  params:
    github: "pytorch/vision:v0.5.0"
    model: "deeplabv3_resnet101"
    pretrained: true
  is_load_ckpt: False
  load_dir:  ''
  load_file: ''