model:
  name: SimpleNet
#  target: graphs.models.simplenet.get_model
#  params:
#    n_channels: ${dataset.data_channel}
#    n_classes: ${dataset.num_classes}
#    bilinear: true
#    last_act: "sigmoid"