dataset:
  name: cremi
  target: datasets_loader.cremi.cremiDataLoader

  data_channel: 1
  num_classes: 2 # (cell & Background )

  use_target_n_channels: False
  use_ImgNet_nor: False

  lbl_encode_base: 25
  data_size: [1250, 1250]

  # Below are hyperparameters depended on running mode
  # running mode = "train"
  train:
    raw_path: "data/CREMI/train/raw"
    label_path: "data/CREMI/train/label"
    test_raw_path: "data/CREMI/test/raw"

    down_scale: 1

    split_ratio: 0.8

    shuffle_data_set: true
    batch_size_train: 32 # 32(size 130), 6(512), 8(256)
    batch_size_valid: 32 # 32(size 130), 6(512), 8(256)

    relabel: false
    dilation: 0
    erosion: 1
    thres_remove_tiny: 20

  # running mode = "fromSeg"
  fromSeg:
    raw_path: "data/CREMI/train/raw"
    label_path: "data/CREMI/train/label"
    start_from: 100
    batch_size: 1
    lbl_encode_base: 25


  # running mode = "deploy"
  deploy:
    raw_path: "data/CREMI/segmentation_result/raw"
    label_path: "data/CREMI/segmentation_result/label"
    start_from: 100
    batch_size: 1
    lbl_encode_base: 25









