# ------------------------------------
# Main configuration yaml for training
# ------------------------------------

defaults:
  - tensorboard: train
  - hydra/output: train

agent:
  name: MendBinSegAgent
  cls: agents.MendBinSeg.MendBinSegAgent

running_mode: train # test, fromSeg

ps_name: ${running_mode}_${agent.name}

exp_name: "\
  ${agent.name}_${model.name}_${model.params.n_channels}_\
  size_${input_size}_\
  lr_${optimizer.params.lr}_${scheduler.params.milestones}_\
  batch_${dataset.train.batch_size_train}_\
  "

gpu_id: 7
seed: 2020
max_epoch: 1000

# Define epoch period for tasks
period:
  log_img_train: 2
  save_checkpoint: 100

input_size: [160, 160]

use_classes: true
output_channel: 1

classes: ['background', 'cell'] #cremi

model:
  name: MendSegNet
  cls: graphs.models.RecSeed.MendSegNet
  params:
    in_channels: [1,1]
    out_channels: ${output_channel}
    n_channels: [64,128,256,512,1024]
    last_act: "sigmoid"
    bilinear: true


loss:
  name: BCEWithLogitsLoss #MSELoss
  cls: torch.nn.BCEWithLogitsLoss


optimizer:
  name: Adam # Adam, SGD
  cls: torch.optim.Adam
  params:
    lr: 1e-4 # 1e-3, 1e-4, 1e-7
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.99
    amsgrad: false


scheduler:
  use: true
  begin_step: 0
  run_on_epoch: true
  name: MultiStepLR
  cls: torch.optim.lr_scheduler.MultiStepLR
  params:
    milestones: [20]
#    milestones: []
    gamma: 0.1


dataset:
  name: cremi
  cls: datasets_loader.cremi.cremiDataLoader

  data_channel: 1
  num_classes: 2 # (cell & Background )

  use_target_n_channels: False
  use_ImgNet_nor: False

  lbl_encode_base: 25
  data_size: [1250, 1250]

  # Below are hyperparameters depended on running mode
  # running mode = "train"
  train:
    raw_path: "data/CREMI/train/raw"
    label_path: "data/CREMI/train/label"
    test_raw_path: "data/CREMI/test/raw"

    down_scale: 1

    split_ratio: 0.8

    shuffle_data_set: true
    batch_size_train: 16 # 64(size 130), 16(256)
    batch_size_valid: 16 # 64(size 130), 16(256)

    relabel: false
    dilation: 0
    erosion: 1
    thres_remove_tiny: 20


ckpt:
  load_dir_default:  '${prj_dir}/pretrained_weights'
  load_file_default: 'load_sample.pt'
  load_dir:  '' #''
  load_file: ''

  save_dir: './ckpt/'
  save_with_name: ${agent.name} #null or {agent.name}_${classes} or ${agent.name}


test_yaml: null
# --------------------
# Assign later in code
# --------------------
curr_dir: ???
prj_dir: ???
