# ------------------------------------
# Main configuration yaml for training
# ------------------------------------

defaults:
  - tensorboard: train
  - agent: SeedRecover
  - hydra/output: train

running_mode: train # test, fromSeg

ps_name: ${running_mode}_${agent.name}

exp_name: "\
  ${agent.name}_${model.name}_${model.params.n_channels}_\
  addErrLBL:${addErrLBL}${model.params.in_channels}_\
  attMode:${model.params.att_mode}_\
  size:${input_size}_\
  lr:${optimizer.params.lr}_${scheduler.params.milestones}_\
  batch:${dataset.train.batch_size_train}_\
  breakBdrMax:${erroneous.breakBdr.max_nSeed}_\
  makeBdrMax:${erroneous.makeBdr.max_nSeed}\
  "

addErrLBL: toInput # toInput, toMask, false

gpu_id: 7
seed: 2020


input_size: [160, 160]
ksize: [31, 31] #[51, 51] # [31, 31]
nmu: 0
nsig: 1

erroneous:
  noisy_err_coor:
    min_nSeed: 0
    max_nSeed: 3
  breakBdr:
    ksize: [31, 31] # ${ksize}
    ksize_ratio: [0.2, 1]
    min_nSeed: 0
    max_nSeed: 10 #6
    remove_nerr: true
    remove_min_nSeed: 0
    remove_max_nSeed: 2
#  makeBdr:
#    ksize: ${ksize}
#    ksize_ratio: [0.2, 1]
#    min_nSeed: 0
#    max_nSeed: 2
#    remove_nerr: true
#    remove_min_nSeed: 0
#    remove_max_nSeed: 1
#    mode: blank # "split" or "blank"

output_channel: 1
classes: ['background', 'cell'] #cremi

model:
  name: RecSeedNet
  target: graphs.models.RecSeed.RecSeedNet
  params:
    att_mode: g+x+c # g+x+c , g+c , (g+x)*c
    in_channels: [2,1] # [EM, seedmap]
    out_channels: ${output_channel}
    n_channels: [64,128,256,512,1024]
    last_act: "sigmoid"
    bilinear: true
    act_layer: leaky_relu

seg_model:
  name: unet
  target: graphs.models.unet.UNet
  params:
    n_channels: ${dataset.data_channel}
    n_classes: ${output_channel}
    bilinear: false
    last_act: "sigmoid" # "sigmoid" "softmax"


loss:
  name: BCEWithLogitsLoss #MSELoss
  target: torch.nn.BCEWithLogitsLoss

ckpt:
  load_dir_default:  '${prj_dir}/pretrained_weights'
  load_file_default: 'load_sample.pt'
  load_dir:  '${prj_dir}/pretrained_weights' #''
  load_file: '06_42_56_SeedRecAgent2.pt'
  load_file_segnet: 'SegNet.pt'

  save_dir: './ckpt/'
  save_with_name: ${agent.name}_${classes}




dataset:
  name: cremi
  target: datasets_loader.cremi.cremiDataLoader

  data_channel: 1
  num_classes: 2 # (cell & Background )

  use_target_n_channels: False
  use_ImgNet_nor: False

  lbl_encode_base: 25
  data_size: [1250, 1250]

  # Below are hyperparameters depended on running mode
  # running mode = "train"
  train:
    raw_path: "data/CREMI/train/raw"
    label_path: "data/CREMI/train/label"
    test_raw_path: "data/CREMI/test/raw"

    split_ratio: 0.8 # split train and val
    shuffle_data_set: false #

    batch_size_train: 16 # 16(160), 4
    batch_size_valid: 16 # 16(160), 4

    lbl2kchannel:
      use: false
      k_channel: 2
    shuffle_Maxlbl: true

    aug:
      down_scale: 1
      RandomSizedCrop:
        use: false # true
        min_height: 64
        to_size: ${input_size}

    thres_remove_tiny: 20




# --------------------
# Assign later in code
# --------------------
curr_dir: ???
prj_dir: ???




